replace sketchy action with simple curl

diff --git a/.github/workflows/jarvis-code.yml b/.github/workflows/jarvis-code.yml
--- a/.github/workflows/jarvis-code.yml
+++ b/.github/workflows/jarvis-code.yml
@@ -25,9 +25,15 @@ jobs:
       - name: Check out code
         uses: actions/checkout@v3
       - name: Check GitHub Status
-        # Source of GitHub Action in line 30: 
-        # https://github.com/dduzgun-security/secure-code-game-action
-        uses: dduzgun-security/secure-code-game-action@dc70b85ad674f6e93657401f3933622870372093 # v1.0
-        with:
-          who-to-greet: "Jarvis, obviously ..."
-          get-token: "token-4db56ee8-dbec-46f3-96f5-32247695ab9b"
+        run: |
+          echo "Checking GitHub Status"
+          # Run the curl command and save the output (the HTTP status code) in a variable
+          status_code=$(curl -s -o /dev/null -w "%{http_code}" https://githubstatus.com/api/v2/status.json)
+
+          # Compare the status code with 200 OK
+          if [ $status_code -ne 200 ]; then
+              echo "GitHub status is not OK as expected."
+              exit 1 # This will cause the workflow to fail
+          else
+              echo "GitHub status is OK."
+          fi
